# Generated by Django 4.2.2 on 2023-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiMathpad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_file',
            field=models.ImageField(upload_to='db_images/'),
        ),
    ]
