# Generated by Django 4.2.2 on 2023-06-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiMathpad', '0002_alter_imagedata_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fractions', models.BooleanField(default=False)),
                ('exponentials', models.BooleanField(default=False)),
                ('roots', models.BooleanField(default=False)),
                ('summations', models.BooleanField(default=False)),
                ('logs', models.BooleanField(default=False)),
                ('trigonometries', models.BooleanField(default=False)),
                ('derivatives', models.BooleanField(default=False)),
                ('integrations', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('fractions', 'exponentials', 'roots', 'summations', 'logs', 'trigonometries', 'derivatives', 'integrations')},
            },
        ),
        migrations.AddField(
            model_name='imagedata',
            name='exp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aiMathpad.expressiontype'),
        ),
    ]
