# Generated by Django 4.2.2 on 2023-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiMathpad', '0004_alter_imagedata_image_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_label',
            field=models.CharField(default='', max_length=400),
        ),
    ]
