version: '3'

services:
  db_postgres:
    image: postgres:latest
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: AIMathpad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - database_network

  web:
    build: 
      context: .
      args:
        - INTERACTIVE_SHELL=true
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/AIMathpad/backend
    ports: #host:docker<-port mapping
      - "7000:8000" #backend port
      - "5000:5000" #mlflow ui port
    environment:
      - POSTGRES_DBL=AIMathpad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - HOST_DOMAIN=192.168.20.11
      - DEBUG=True
    networks:
      - database_network
    depends_on:
      - db_postgres

networks:
  database_network:
    driver: bridge
