version: '3'

services:
  db_postgres:
    image: postgres:latest
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: AIMathpad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - database_network

  web:
    build: 
      context: .
      args:
        - INTERACTIVE_SHELL=true
    # command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/app_dev
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DBL=AIMathpad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so.20
    networks:
      - database_network
    depends_on:
      - db_postgres

networks:
  database_network:
    driver: bridge
