# Generated by Django 4.2.2 on 2023-07-07 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=250)),
                ('num_images', models.IntegerField(default=0)),
                ('pickled_stats', models.BinaryField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('path', models.CharField(max_length=250)),
                ('repo_path', models.CharField(max_length=250)),
                ('mlflow_experiment_id', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodels', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_dlmodels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DlModelDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodeldatasets', to=settings.AUTH_USER_MODEL)),
                ('dl_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodeldatasets', to='dataAdmin.dlmodel')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_dlmodeldatasets', to=settings.AUTH_USER_MODEL)),
                ('parent_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodeldatasets', to='dataAdmin.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DlModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodelVersions', to=settings.AUTH_USER_MODEL)),
                ('dl_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodelVersions', to='dataAdmin.dlmodel')),
                ('dl_model_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlmodelVersions', to='dataAdmin.dlmodeldataset')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_dlmodelVersions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dlmodel',
            name='primary_dl_model_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlmodels', to='dataAdmin.dlmodelversion'),
        ),
    ]
