# Generated by Django 4.2.2 on 2023-07-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dlmodel',
            name='mlflow_experiment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dlmodel',
            name='primary_dl_model_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlmodels', to='dataAdmin.dlmodelversion'),
        ),
        migrations.AlterField(
            model_name='dlmodeldataset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dlmodelversion',
            name='dl_model_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlmodelVersions', to='dataAdmin.dlmodeldataset'),
        ),
    ]
